Doc/adding local db dev guidelines
Pjaijai/Referalah pull request #146
Opened 2023-10-17 18:51 UTC by Pjaijai

2023-10-18 22:52 UTC, marukosy124 requested changes

2023-10-18 22:52 UTC, marukosy124 commented on DEVELOPER.md
> +2. Run `supabase login` which your `personal access token` from supabase.
"which" should be "with"?

2023-10-19 01:23 UTC, Pjaijai commented on DEVELOPER.md
> +2. Run `supabase login` which your `personal access token` from supabase.
Thanks. Updated. Please check

2023-10-20 06:12 UTC, yaucp approved these changes

2023-10-20 12:19 UTC, merged