[Docs] Improvements and breaking down
Pjaijai/Referalah pull request #257
Opened 2023-11-18 16:18 UTC by VardyNg

This PR contains enhancement as documented in https://github.com/Pjaijai/Referalah/issues/253.

2023-11-18 20:38 UTC, Pjaijai requested changes
Definitely enhance the document ! Such a Great Job !

2023-11-18 20:38 UTC, Pjaijai commented on docs/Backend.md
> +    ```
The steps should be 1 2 3 ?

2023-11-18 20:38 UTC, Pjaijai commented on docs/Backend.md
> +
I believe the handle_new_user function do not need to be created by using sql script because it could be migrated. The problem is on on_auth_user_created.

I think just running the code below will fix the problem.
```create or replace trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
```

2023-11-18 20:38 UTC, Pjaijai commented on docs/Backend.md
> +
Could you please mention http://localhost:54324/ for receiving supabase auth email

2023-11-18 20:39 UTC, Pjaijai commented
For md file, I suggest to re-name the file name with all upper case letter. If there is some practice or convention I missed out, please let me know

2023-11-18 20:48 UTC, VardyNg commented on docs/Backend.md
> +    ```
I intended to make it 1 1 1, as in GitHub and VS Code will interpret it as 1 2 3, as shown below:
<img width="385" alt="image" src="https://github.com/Pjaijai/Referalah/assets/24868846/b68a0f47-4ca2-4290-b3eb-e40680b88bf5">
Doing in this way can save effort on refactoring in the future, you don't want to update the index manually when a step is added or removed.

2023-11-18 20:49 UTC, VardyNg commented on docs/Backend.md
> +
This part is already mentioned in the Frontend.md, do you think we need to also mention this here?

2023-11-18 20:51 UTC, VardyNg commented
> For md file, I suggest to re-name the file name with all upper case letter. If there is some practice or convention I missed out, please let me know

I think so, let me rename the file to make them all in capital

2023-11-18 20:58 UTC, Pjaijai commented on docs/Backend.md
> +
Yes please do. This a frequently asked question. I suggest putting the whole url out.

2023-11-18 20:59 UTC, VardyNg commented on docs/Backend.md
> +
I am not sure about this part, I think we can do a PoC to clear this out

2023-11-18 21:09 UTC, Pjaijai commented on docs/Backend.md
> +
After you restart the project and check on local panel, you will see the function handle_new_user but not the trigger. User cannot be added to the user table.

```
create or replace trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
```

After running this, the user should be created successfully.

2023-11-18 21:21 UTC, VardyNg commented on docs/Backend.md
> +
Added in ca133c02fd8805ff18f2cfb856172bbb8ce5d08b

2023-11-21 17:23 UTC, ken31ee commented
Can we add a part pointing out where to find the virtual email inbox in supabase since this necessary to be able to login in local dev env.

2023-11-21 20:19 UTC, Pjaijai commented
> Can we add a part pointing out where to find the virtual email inbox in supabase since this necessary to be able to login in local dev env.

Yes. It is in the doc now

2023-11-21 22:44 UTC, Pjaijai commented on docs/Backend.md
> +
@VardyNg I tested on my local. Just running create trigger on_auth_user_created is good enough. If you want to try, run supabase db reset.

2023-11-22 04:22 UTC, VardyNg commented on docs/Backend.md
> +
I will trust you on that, as I am still getting familiar with it. 
I think we can close this conversation and merge the change if not other issue.

2023-11-22 11:48 UTC, Pjaijai commented on docs/Backend.md
> +
So it is good to remove create function public.handle_new_user() part ?

2023-11-23 03:24 UTC, Pjaijai approved these changes
GJ

2023-11-23 03:24 UTC, merged